[2022-03-04 13:01:37,087: INFO: prepare_base_model]: 
********************
[2022-03-04 13:01:37,087: INFO: prepare_base_model]: >>>>> stage prepare a base model  started <<<<<
[2022-03-04 13:01:37,098: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:02:19,182: INFO: common]: created directory at: artifacts\models
[2022-03-04 13:02:19,272: INFO: prepare_base_model]: base model is saved at artifacts\models\base_models.h5
[2022-03-04 13:02:19,343: INFO: prepare_base_model]: >>>>> stage prepare a base model  completed!<<<<<

[2022-03-04 13:13:32,258: INFO: prepare_base_model]: 
********************
[2022-03-04 13:13:32,260: INFO: prepare_base_model]: >>>>> stage prepare a base model  started <<<<<
[2022-03-04 13:13:32,261: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:14:09,458: INFO: transfer_learning]: 
********************
[2022-03-04 13:14:09,458: INFO: transfer_learning]: >>>>> stage transferlearning started <<<<<
[2022-03-04 13:14:09,459: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:14:09,459: ERROR: transfer_learning]: load_model() missing 1 required positional argument: 'filepath'
Traceback (most recent call last):
  File "C:\Project_work\transfer-learning\src\transfer_learning.py", line 39, in <module>
    main(config_path=parsed_args.config)
  File "C:\Project_work\transfer-learning\src\transfer_learning.py", line 27, in main
    base_model = tf.keras.models.load_model()
  File "C:\Users\fazlu\anaconda3\envs\tLearning\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\fazlu\anaconda3\envs\tLearning\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
TypeError: load_model() missing 1 required positional argument: 'filepath'
[2022-03-04 13:15:22,854: INFO: transfer_learning]: 
********************
[2022-03-04 13:15:22,854: INFO: transfer_learning]: >>>>> stage transferlearning started <<<<<
[2022-03-04 13:15:22,855: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:15:22,985: INFO: transfer_learning]: >>>>> stage transferlearning completed!<<<<<

[2022-03-04 13:36:54,594: INFO: transfer_learning]: 
********************
[2022-03-04 13:36:54,594: INFO: transfer_learning]: >>>>> stage transferlearning started <<<<<
[2022-03-04 13:36:54,595: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:36:54,706: INFO: transfer_learning]: >>>>> stage transferlearning completed!<<<<<

[2022-03-04 13:41:26,704: INFO: transfer_learning]: 
********************
[2022-03-04 13:41:26,704: INFO: transfer_learning]: >>>>> stage transferlearning started <<<<<
[2022-03-04 13:41:26,705: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:41:26,820: ERROR: transfer_learning]: module 'keras.api._v2.keras' has no attribute 'model'
Traceback (most recent call last):
  File "C:\Project_work\transfer-learning\src\transfer_learning.py", line 58, in <module>
    main(config_path=parsed_args.config)
  File "C:\Project_work\transfer-learning\src\transfer_learning.py", line 41, in main
    new_model = tf.keras.model.Sequential(base_layers)
AttributeError: module 'keras.api._v2.keras' has no attribute 'model'
[2022-03-04 13:42:00,224: INFO: transfer_learning]: 
********************
[2022-03-04 13:42:00,224: INFO: transfer_learning]: >>>>> stage transferlearning started <<<<<
[2022-03-04 13:42:00,225: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:42:00,390: INFO: transfer_learning]: >>>>> stage transferlearning completed!<<<<<

[2022-03-04 13:43:09,501: INFO: transfer_learning]: 
********************
[2022-03-04 13:43:09,501: INFO: transfer_learning]: >>>>> stage transferlearning started <<<<<
[2022-03-04 13:43:09,502: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:43:09,638: ERROR: transfer_learning]: 'output layer/' is not a valid root scope name. A root scope name has to match the following pattern: ^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$
Traceback (most recent call last):
  File "C:\Project_work\transfer-learning\src\transfer_learning.py", line 58, in <module>
    main(config_path=parsed_args.config)
  File "C:\Project_work\transfer-learning\src\transfer_learning.py", line 43, in main
    new_model.add(
  File "C:\Users\fazlu\anaconda3\envs\tLearning\lib\site-packages\tensorflow\python\training\tracking\base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\fazlu\anaconda3\envs\tLearning\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\fazlu\anaconda3\envs\tLearning\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
ValueError: 'output layer/' is not a valid root scope name. A root scope name has to match the following pattern: ^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$
[2022-03-04 13:43:30,317: INFO: transfer_learning]: 
********************
[2022-03-04 13:43:30,317: INFO: transfer_learning]: >>>>> stage transferlearning started <<<<<
[2022-03-04 13:43:30,318: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-04 13:43:30,493: INFO: transfer_learning]: >>>>> stage transferlearning completed!<<<<<

